FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# shippingManagement

Polls is a simple API allowing consumers to view shipping list.

## Shipping Collection [/shippingManagement]

### List All shipping Items [GET]

+ Response 200 (application/json)

        [
            {
                "shipping": [
                    {
                        "id": 102030,
                        "client": "Carla Martinez",
                        "address": "Av Vitacura 2939 piso 6",
                        "date": "01/01/2019",
                        "status": "en preparacion"
                    }, {
                         "id": 102031,
                        "client": "Arturo Gomez",
                        "address": "Las condes 123",
                        "date": "02/01/2019",
                        "status": "preparado"
                    }, {
                         "id": 102032,
                        "client": "Javier Lopez",
                        "address": "Av Vitacura 2939 piso 6",
                        "date": "02/01/2019",
                        "status": "sin stock"
                    }, {
                         "id": 102033,
                        "client": "Catalina Perez",
                        "address": "Calle Isidora 2245",
                        "date": "01/01/2019",
                        "status": "preparado"
                    }
                ]
            }
        ]

### Create a New shipping [POST]

Create a new shipping order to one customer.

+ Request (application/json)

        {
            "client": "client Name",
            "address": "String",
            "date": "01/01/2019",
            "status": "status"
        }

+ Response 201 (application/json)

    + Body

            {
                "id": 102036
            }